
# -*- coding: utf-8 -*-
"""generador_datos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E-NlFpQvGlgLvZVwtiPuWKCKUXf3QEVF
"""

import string
#lista base de sintomas
partes = ['abdomen','espalda','pecho','oído','cabeza','pelvis','dientes','recto','piel']
sensaciones = ['escalofríos','fiebre','parestesia','aturdimiento','presincope','boca seca','nausea','desaliento','somnolencia','sudoración','sed','cansancio','debilidad']
acciones = ['respirar normalmente','escuchar normalmente','ver normalmente','mover un lado','defecar','orinar','dormir','oler','tragar','saborear','sentir','hablar']
me_duele = ['dolor de ' + i for i in partes]
no_puedo = ['no puede ' + i for i in acciones]
sintomas = me_duele + no_puedo + sensaciones

#lista base de signos
signos = ['masa abdominal','obesidad','alogia','anasarca','hematoma','alucinaciones',
          'manchas', 'presión intracraneal', 'hedor hepatico','cianosis','chancro', 'crepitación','linea nigra','rectorragia','exantema','emesis', 'Gingivorragia',
    'Gliosis','Goma granulomatosa','Gránulos de Schüffner','Hematemesis','Hematocele','Hematoma','Hematuria','Hemoptisis','Hemorragia','Hemorragia digestiva baja','Hemorragia gastrointestinal','Hepatomegalia',
'Hinchazón',
'Hinchazón abdominal',
'Hiperfosfatemia',
'Hiperglucemia',
'Hipertelorismo']



sintomas_file = open("sintomas.txt","w+")
for cosa in signos:
    sintomas_file.write(cosa)
    sintomas_file.write('\n')
signos_file = open("signos.txt","w+")
for cosa in sintomas:
    signos_file.write(cosa)
    signos_file.write('\n')
