# -*- coding: utf-8 -*-
"""generador_datos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E-NlFpQvGlgLvZVwtiPuWKCKUXf3QEVF
"""

import string
#lista base de sintomas
partes = ['abdomen','espalda','pecho','oído','cabeza','pelvis','dientes','recto','piel']
sensaciones = ['escalofríos','fiebre','parestesia','aturdimiento','presincope','boca seca','nausea','desaliento','somnolencia','sudoración','sed','cansancio','debilidad']
acciones = ['respirar normalmente','escuchar normalmente','ver normalmente','mover un lado','defecar','orinar','dormir','oler','tragar','saborear','sentir','hablar']
me_duele = ['dolor de ' + i for i in partes]
no_puedo = ['no puede ' + i for i in acciones]
sintomas = me_duele + no_puedo + sensaciones

#lista base de signos
signos = ['masa abdominal','obesidad','alogia','anasarca','hematoma','alucinaciones',
          'manchas', 'presión intracraneal', 'hedor hepatico','cianosis','chancro', 'crepitación','linea nigra','rectorragia','exantema','emesis', 'Gingivorragia',
    'Gliosis','Goma granulomatosa','Gránulos de Schüffner','Hematemesis','Hematocele','Hematoma','Hematuria','Hemoptisis','Hemorragia','Hemorragia digestiva baja','Hemorragia gastrointestinal','Hepatomegalia',
'Hinchazón',
'Hinchazón abdominal',
'Hiperfosfatemia',
'Hiperglucemia',
'Hipertelorismo']
#Nombres de enfermedades

Nombres = list(string.ascii_lowercase)

from random import randint
condiciones_usadas = set()
nombres_usados = set()
f= open("muestra.txt","w+")
for i in range(100):
  longitud_nombre = randint(3,50)
  nombre = []
  longitud_sintoma = randint(3,len(sintomas)-1)
  sintoma_lista = []
  longitud_signos = randint(3,9)
  signos_lista = []
  while True:
    sintomas_usados =  set()
    signos_usados = set()
    for e in range(longitud_nombre):
      nombre.append(Nombres[randint(0,len(Nombres)-1)])
    for e in range(longitud_signos):
      random_signo = signos[randint(0,len(signos)-1)]
      while random_signo in signos_usados:
        random_signo = signos[randint(0,len(signos)-1)]
      signos_usados.add(random_signo)
      signos_lista.append(random_signo)
    for e in range(longitud_sintoma):
      random_sintoma = sintomas[randint(0,len(sintomas)-1)]
      while random_sintoma in sintomas_usados:
        random_sintoma = sintomas[randint(0,len(sintomas)-1)]
      sintomas_usados.add(random_sintoma)
      sintoma_lista.append(random_sintoma)
    signos_lista.sort()
    sintoma_lista.sort()
    t_sin = tuple(sintoma_lista)
    t_sig = tuple(signos_lista)
    t_n = tuple(nombre)
    if (t_sig,t_sin) in condiciones_usadas or t_n in nombres_usados:
      nombre = []
      sintoma_lista = []
      signos_lista = []
    else:
      nombres_usados.add(t_n)
      condiciones_usadas.add((t_sig,t_sin))
      break
  nombre_string = ''
  sintomas_string = ''
  signos_string = ''
  for l in range(len(nombre)):
    nombre_string += nombre[l]
  for s in range(len(sintoma_lista)):
    sintomas_string += sintoma_lista[s]
    if s < len(sintoma_lista)-1:
      sintomas_string += ', '
  for s in range(len(signos_lista)):
    signos_string += signos_lista[s]
    if s < len(signos_lista)-1:
      signos_string += ', '
  f.write("Enfermedad: "+nombre_string)
  f.write('\n') 
  f.write("Sintomas: "+sintomas_string)
  f.write('\n') 
  f.write("Signos: "+signos_string) 
  f.write('\n') 
  f.write('\n')  
f.close
